# Generated by Django 4.0.1 on 2022-01-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Sku',
            field=models.CharField(help_text='Sku', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_i',
            field=models.CharField(help_text='price', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='wight_i',
            field=models.CharField(help_text='wight', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(help_text='Description', max_length=200),
        ),
    ]
