# Generated by Django 4.0.1 on 2022-01-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_item_sku_item_price_i_item_wight_i_alter_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='wight_i',
            new_name='weight_i',
        ),
    ]
